### ISSUE TITLE
Run this code on GPU

### ISSUE THREAD

**Issue by crypt0inf0** [MattyAB/BitcoinMiner#3]
Hi, Do you know how to run this code on GPU?

**Comment by MattBeton** [comment]
For running code like this on an Nvidia GPU, the miner would need to be written in CUDA instead of C++; on top of this, this code is also not nearly optimised enough for production mining. A production CPU miner would primarily be written in assembly instead of C/C++. For example, see [cpuminer](https://github.com/pooler/cpuminer).
